export function pdfTemplate(inspection, settings = {}) {
    const issues = inspection.rooms.flatMap((room) =>
        room.items
            .filter((item) => item.status === 'issue')
            .map((item) => ({ ...item, roomName: room.name }))
    );

    const roomRows = inspection.rooms
        .map((room) => {
            const issueCount = room.items.filter((i) => i.status === 'issue').length;
            return `<tr>
        <td>${room.name}</td>
        <td class="${issueCount > 0 ? 'issue' : 'ok'}">${issueCount > 0 ? '⚠ Issues Found' : '✓ OK'}</td>
        <td>${issueCount} issue(s)</td>
      </tr>`;
        })
        .join('');

    const detailedRows = inspection.rooms
        .map(
            (room) => `
      <div class="room-heading">${room.name}</div>
      <table>
        <tr><th>Item</th><th>Status</th><th>Notes</th></tr>
        ${room.items
                    .map(
                        (item) => `
          <tr>
            <td>${item.name}</td>
            <td class="${item.status}">${item.status === 'ok' ? '✓ OK' : item.status === 'issue' ? '⚠ Issue' : '— N/A'
                            }</td>
            <td>${item.note || '—'}</td>
          </tr>`
                    )
                    .join('')}
      </table>
    `
        )
        .join('');

    const issueCards = issues
        .map(
            (item) => `
      <div class="issue-card">
        <div class="issue-room">${item.roomName} · ${item.name}
          <span class="severity">${item.note && item.note.length > 20 ? 'MAJOR' : 'MINOR'}</span>
        </div>
        <div class="issue-note">${item.note || 'No description.'}</div>
        ${item.photos.map((uri) => `<img class="photo" src="${uri}" />`).join('')}
      </div>`
        )
        .join('');

    return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>
    body { font-family: Georgia, serif; color: #111; padding: 40px; }
    .header { display:flex; justify-content:space-between; border-bottom:2px solid #111; padding-bottom:16px; margin-bottom:24px; }
    .title { font-size:28px; font-weight:bold; letter-spacing:2px; }
    .ref { font-size:11px; color:#666; margin-top:4px; }
    .logo { width:80px; height:80px; object-fit:contain; }
    table { width:100%; border-collapse:collapse; margin-bottom:16px; }
    th { background:#f5f5f5; padding:8px 10px; font-size:12px; text-align:left; text-transform:uppercase; }
    td { padding:8px 10px; font-size:13px; border-bottom:1px solid #eee; vertical-align:top; }
    .ok { color:#16a34a; font-weight:bold; }
    .issue { color:#dc2626; font-weight:bold; }
    .na { color:#999; }
    .room-heading { font-size:15px; font-weight:bold; margin:20px 0 8px; }
    .issue-card { border:1px solid #fca5a5; background:#fff5f5; padding:12px; margin-bottom:10px; border-radius:4px; }
    .issue-room { font-size:11px; font-weight:bold; color:#dc2626; text-transform:uppercase; }
    .severity { float:right; background:#dc2626; color:#fff; padding:2px 6px; border-radius:3px; font-size:10px; }
    .issue-note { font-size:13px; margin-top:6px; }
    .photo { width:120px; height:90px; object-fit:cover; margin:6px 4px 0 0; border-radius:3px; }
    .footer { margin-top:40px; border-top:1px solid #ddd; padding-top:12px; text-align:center; font-size:11px; color:#999; }
    .section-title { font-size:13px; font-weight:bold; letter-spacing:2px; text-transform:uppercase; border-bottom:1px solid #ddd; padding-bottom:6px; margin:24px 0 12px; }
    .meta p { margin:4px 0; font-size:13px; }
  </style></head><body>

  <div class="header">
    <div>
      <div class="title">INSPECTION REPORT</div>
      <div class="ref">REF: IP-${inspection.id.slice(-8).toUpperCase()}</div>
    </div>
    ${settings.logoUri ? `<img class="logo" src="${settings.logoUri}" />` : ''}
  </div>

  <div class="meta">
    <p><strong>Property:</strong> ${inspection.address}</p>
    <p><strong>Date:</strong> ${inspection.date}</p>
    <p><strong>Type:</strong> ${inspection.type} Inspection</p>
    <p><strong>Inspector:</strong> ${settings.inspectorName || 'N/A'}</p>
    ${settings.companyName ? `<p><strong>Company:</strong> ${settings.companyName}</p>` : ''}
    ${settings.phone ? `<p><strong>Phone:</strong> ${settings.phone}</p>` : ''}
    ${settings.email ? `<p><strong>Email:</strong> ${settings.email}</p>` : ''}
  </div>

  <div class="section-title">Room Summary</div>
  <table><tr><th>Room</th><th>Status</th><th>Issues</th></tr>${roomRows}</table>

  <div class="section-title">Detailed Checklist</div>
  ${detailedRows}

  ${issues.length > 0 ? `<div class="section-title">Flagged Issues</div>${issueCards}` : ''}

  <div class="footer">Generated by InspectPro · ${inspection.date} · ${settings.companyName || 'InspectPro'}</div>
  </body></html>`;
}
